server:
  port: 8080

app:
  name: bitcoin
  isCloud: false

aws:
  profile: default
  region: us-east-1
  dynamodb:
    endpoint: http://localhost:4566
  ses:
    config:
      from: mlex.alba@gmail.com
      to: mlex.alba@gmail.com

analytics:
  elementsInTheMiddle: 5

stock:
  data:
    use-real: false
  api:
    key: YOUR_API_KEY_HERE
    base-url: https://www.alphavantage.co/query